# Turns a binary file into a C source defining `const unsigned char SYMBOL[]`
# and `const size_t SYMBOL_size`. Portable replacement for xxd -i / ld -b binary.
#
# cmake -DINPUT=<file> -DOUTPUT=<file.c> -DSYMBOL=<name> -P EmbedFile.cmake
foreach(var INPUT OUTPUT SYMBOL)
  if(NOT DEFINED ${var})
    message(FATAL_ERROR "EmbedFile.cmake: ${var} is not set")
  endif()
endforeach()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hex_length)
math(EXPR size "${hex_length} / 2")

# "0a1b2c" -> "0x0a,0x1b,0x2c," with a line break every 16 bytes.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" hex "${hex}")

file(WRITE "${OUTPUT}"
  "// Generated by EmbedFile.cmake from ${INPUT}; do not edit.\n"
  "#include <stddef.h>\n"
  "const unsigned char ${SYMBOL}[] = {\n${hex}\n};\n"
  "const size_t ${SYMBOL}_size = ${size};\n")
